"""add hashed_refresh_token to user

Revision ID: 0f2ce4cae13f
Revises: afdd04d1e09b
Create Date: 2026-07-17 21:46:12.134762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2ce4cae13f'
down_revision = 'afdd04d1e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_refresh_token')
    # ### end Alembic commands ###
