"""Add entities tables

Revision ID: 4758804d863e
Revises: 7fcb4c53cafc
Create Date: 2026-03-24 21:54:13.746530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4758804d863e'
down_revision = '7fcb4c53cafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('entity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_entity_type_id'), 'entity_type', ['id'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alternative_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_active', 'entity', ['is_active', 'name'], unique=False)
    op.create_index(op.f('ix_entity_category_id'), 'entity', ['category_id'], unique=False)
    op.create_index('ix_entity_category_type', 'entity', ['category_id', 'entity_type_id'], unique=False)
    op.create_index(op.f('ix_entity_entity_type_id'), 'entity', ['entity_type_id'], unique=False)
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=False)
    op.create_index(op.f('ix_entity_is_active'), 'entity', ['is_active'], unique=False)
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristic_entity_id'), 'characteristic', ['entity_id'], unique=False)
    op.create_index('ix_characteristic_entity_type', 'characteristic', ['entity_id', 'type'], unique=False)
    op.create_index(op.f('ix_characteristic_id'), 'characteristic', ['id'], unique=False)
    op.create_table('entity_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_origin_id', sa.Integer(), nullable=False),
    sa.Column('entity_destination_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_destination_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_origin_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_origin_id', 'entity_destination_id', 'relation_type', name='uq_entity_relation_unique')
    )
    op.create_index('ix_entity_relation_destination', 'entity_relation', ['entity_destination_id'], unique=False)
    op.create_index(op.f('ix_entity_relation_entity_destination_id'), 'entity_relation', ['entity_destination_id'], unique=False)
    op.create_index(op.f('ix_entity_relation_entity_origin_id'), 'entity_relation', ['entity_origin_id'], unique=False)
    op.create_index(op.f('ix_entity_relation_id'), 'entity_relation', ['id'], unique=False)
    op.create_index('ix_entity_relation_origin', 'entity_relation', ['entity_origin_id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('place_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_department'), 'location', ['department'], unique=False)
    op.create_index(op.f('ix_location_entity_id'), 'location', ['entity_id'], unique=False)
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_entity_id'), 'source', ['entity_id'], unique=False)
    op.create_index('ix_source_entity_type', 'source', ['entity_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.alter_column('character', 'type',
               existing_type=postgresql.ENUM('human', 'animal', 'ghost', 'demon', 'apparition', 'spirit', name='charactertype'),
               nullable=False)
    op.alter_column('character', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'unknown', name='gender'),
               nullable=False)
    op.alter_column('character', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('country', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('character', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'unknown', name='gender'),
               nullable=True)
    op.alter_column('character', 'type',
               existing_type=postgresql.ENUM('human', 'animal', 'ghost', 'demon', 'apparition', 'spirit', name='charactertype'),
               nullable=True)
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_index('ix_source_entity_type', table_name='source')
    op.drop_index(op.f('ix_source_entity_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_entity_id'), table_name='location')
    op.drop_index(op.f('ix_location_department'), table_name='location')
    op.drop_table('location')
    op.drop_index('ix_entity_relation_origin', table_name='entity_relation')
    op.drop_index(op.f('ix_entity_relation_id'), table_name='entity_relation')
    op.drop_index(op.f('ix_entity_relation_entity_origin_id'), table_name='entity_relation')
    op.drop_index(op.f('ix_entity_relation_entity_destination_id'), table_name='entity_relation')
    op.drop_index('ix_entity_relation_destination', table_name='entity_relation')
    op.drop_table('entity_relation')
    op.drop_index(op.f('ix_characteristic_id'), table_name='characteristic')
    op.drop_index('ix_characteristic_entity_type', table_name='characteristic')
    op.drop_index(op.f('ix_characteristic_entity_id'), table_name='characteristic')
    op.drop_table('characteristic')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_is_active'), table_name='entity')
    op.drop_index(op.f('ix_entity_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type_id'), table_name='entity')
    op.drop_index('ix_entity_category_type', table_name='entity')
    op.drop_index(op.f('ix_entity_category_id'), table_name='entity')
    op.drop_index('ix_entity_active', table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_entity_type_id'), table_name='entity_type')
    op.drop_table('entity_type')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###