"""Add unique fields on character's name

Revision ID: 7fcb4c53cafc
Revises: d15753a0d7f5
Create Date: 2022-09-21 04:20:43.249291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcb4c53cafc'
down_revision = 'd15753a0d7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_name', table_name='character')
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.create_index('ix_character_name', 'character', ['name'], unique=False)
    # ### end Alembic commands ###