"""Remove characters table

Revision ID: d077d52b1166
Revises: 4758804d863e
Create Date: 2026-03-25 00:26:40.106736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd077d52b1166'
down_revision = '4758804d863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_location_department'), table_name='location')
    op.create_index('ix_location_department', 'location', ['department', 'municipality'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_department', table_name='location')
    op.create_index(op.f('ix_location_department'), 'location', ['department'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('human', 'animal', 'ghost', 'demon', 'apparition', 'spirit', name='charactertype'), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'unknown', name='gender'), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('character_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('character_pkey'))
    )
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=True)
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    # ### end Alembic commands ###