"""Add characters

Revision ID: d15753a0d7f5
Revises: cc8968535392
Create Date: 2022-09-20 22:41:08.301217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15753a0d7f5'
down_revision = 'cc8968535392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('human', 'animal', 'ghost', 'demon', 'apparition', 'spirit', name='charactertype'), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='gender'), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###